apiVersion: v1
kind: Service
metadata:
  name: colour
spec:
  type: ClusterIP
  selector:
    app: colour
    version: blue
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: canary
spec:
  type: ClusterIP
  selector:
    app: canary
  ports:
  - port: 80
    targetPort: 80
