replicaCount: 2
backend:
  image: homework-taskboard-backend
  tag: local
frontend:
  image: homework-taskboard-frontend
  tag: local
imagePullPolicy: IfNotPresent
existingSecret: taskboard-db
storageClass: standard
storageSize: 1Gi
ingress:
  enabled: true
  className: traefik
  host: taskboard.local
hpa:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 60
postgresImagePullPolicy: IfNotPresent
postgresImage: postgres:16-alpine
